"""Command-line interface for parsing, solving, generating, and benchmarking CNF."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .benchmarking import run_benchmark, summarize, write_csv_report, write_json_report
from .dimacs import parse_dimacs, read_dimacs, to_dimacs
from .formula import CNFError
from .generator import generate_random_cnf
from .solver import SolveStatus, solve


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="satrl",
        description="Parse, generate, and exactly solve DIMACS CNF formulas.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    solve_parser = subparsers.add_parser("solve", help="solve a DIMACS CNF file")
    solve_parser.add_argument("input", help="path to a DIMACS file, or '-' for stdin")
    solve_parser.add_argument(
        "--max-nodes",
        type=int,
        default=None,
        help="return UNKNOWN after this many search nodes",
    )
    solve_parser.add_argument(
        "--no-preprocess",
        action="store_true",
        help="disable tautology, duplicate, and subsumption preprocessing",
    )
    solve_parser.add_argument("--json", action="store_true", help="emit JSON")
    solve_parser.set_defaults(handler=_handle_solve)

    generate_parser = subparsers.add_parser(
        "generate", help="generate a deterministic random k-CNF instance"
    )
    generate_parser.add_argument("--variables", type=int, required=True)
    generate_parser.add_argument("--clauses", type=int, required=True)
    generate_parser.add_argument("--clause-size", type=int, default=3)
    generate_parser.add_argument("--seed", type=int, required=True)
    generate_parser.add_argument(
        "--planted",
        action="store_true",
        help="generate clauses satisfied by a hidden deterministic assignment",
    )
    generate_parser.add_argument(
        "--output", default="-", help="output DIMACS path, or '-' for stdout"
    )
    generate_parser.set_defaults(handler=_handle_generate)

    benchmark_parser = subparsers.add_parser(
        "benchmark", help="run a reproducible small-instance exact-solver benchmark"
    )
    benchmark_parser.add_argument("--variables", type=int, default=10)
    benchmark_parser.add_argument("--clauses", type=int, default=40)
    benchmark_parser.add_argument("--clause-size", type=int, default=3)
    benchmark_parser.add_argument("--instances", type=int, default=20)
    benchmark_parser.add_argument("--seed", type=int, default=523)
    benchmark_parser.add_argument(
        "--oracle-variable-limit",
        type=int,
        default=16,
        help="cross-check DPLL with enumeration up to this variable count",
    )
    benchmark_parser.add_argument(
        "--output", help="optional .json or .csv destination for per-instance records"
    )
    benchmark_parser.set_defaults(handler=_handle_benchmark)

    return parser


def _read_formula(path: str, *, preprocess: bool):
    if path == "-":
        return parse_dimacs(sys.stdin.read(), preprocess=preprocess)
    return read_dimacs(path, preprocess=preprocess)


def _handle_solve(args: argparse.Namespace) -> int:
    formula = _read_formula(args.input, preprocess=not args.no_preprocess)
    result = solve(formula, max_nodes=args.max_nodes)
    if args.json:
        payload = result.to_dict()
        payload["formula"] = {
            "variables": formula.num_variables,
            "clauses": len(formula.clauses),
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
    else:
        print(f"s {result.status.value}")
        if result.assignment is not None:
            literals = [
                str(variable if value else -variable)
                for variable, value in sorted(result.assignment.items())
            ]
            print(f"v {' '.join(literals)} 0")
        print(
            "c "
            f"verified={str(result.verified).lower()} "
            f"nodes={result.stats.nodes} decisions={result.stats.decisions} "
            f"conflicts={result.stats.conflicts} "
            f"elapsed_ms={result.stats.elapsed_ms:.3f}"
        )
        if result.reason:
            print(f"c {result.reason}")
    return 3 if result.status is SolveStatus.UNKNOWN else 0


def _handle_generate(args: argparse.Namespace) -> int:
    generated = generate_random_cnf(
        args.variables,
        args.clauses,
        args.clause_size,
        seed=args.seed,
        planted=args.planted,
    )
    text = to_dimacs(
        generated.formula,
        comment=(
            f"generated by satrl seed={args.seed} planted={str(args.planted).lower()}"
        ),
    )
    if args.output == "-":
        sys.stdout.write(text)
    else:
        Path(args.output).write_text(text, encoding="utf-8")
    return 0


def _handle_benchmark(args: argparse.Namespace) -> int:
    records = run_benchmark(
        variables=args.variables,
        clauses=args.clauses,
        clause_size=args.clause_size,
        instances=args.instances,
        seed=args.seed,
        oracle_variable_limit=args.oracle_variable_limit,
    )
    summary = summarize(records)
    print(json.dumps(summary, indent=2, sort_keys=True))
    if args.output:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        if output.suffix.lower() == ".json":
            write_json_report(records, output)
        elif output.suffix.lower() == ".csv":
            write_csv_report(records, output)
        else:
            raise ValueError("benchmark output must end in .json or .csv")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
